[package]
name = "ellinofreneia"
version = "0.1.0"
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]

[dependencies]
error-chain = "0.11.0"
structopt = "0.1.0"
structopt-derive = "0.1.0"
loggerv = "0.3.0"
log = "*"