[package]
name = "ellinofreneia"
version = "0.1.0"
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]

[dependencies]
error-chain = "0.11.0"
structopt = "0.1.0"
structopt-derive = "0.1.0"
log = "0.3.8"
loggerv = "0.3.0"
select = "0.4.2"
reqwest = "0.7.3"
rafy = "0.2"